shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('product-category/<str:slug>', views.product_category, name='product-category'),
    path('more_info/<int:id>/', views.more_info, name='more_info'),
]

user/urls.py
from django.urls import path
from . import views


app_name = 'user'

urlpatterns = [
    path('', views.my_account, name='my-account'),
    path('authorization/', views.authorization, name='authorization'),
    path('registration/', views.registration, name='registration'),
    path('edit-account/', views.EditAccount.as_view(), name='edit-account'),
    path('logout/', views.logout, name='logout'),
]

wooddeco/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('my-account/', include('user.urls')),
]

shop/models.py
from django.db import models


class Category(models.Model):
    slug = models.SlugField(default='')
    parent = models.ForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)

    title = models.CharField(max_length=32)

    def __str__(self):
        return self.title


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    img = models.ImageField(upload_to='static/images', null=True, blank=True)
    description = models.TextField( default=" ")
    price = models.DecimalField(max_digits=8, decimal_places=2)
    discount = models.DecimalField(max_digits=8, decimal_places=2, default=0)

    def __str__(self):
        return self.title

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms
from django.core.exceptions import ValidationError


class AuthForm(forms.Form):
    login = forms.CharField(max_length=64, label="Email/username")
    password = forms.CharField(widget=forms.PasswordInput, min_length=6, label='Пароль')


class RegForm(forms.Form):
    email = forms.CharField(max_length=64, label="Email")
    password = forms.CharField(widget=forms.PasswordInput, min_length=6, label='Пароль')


class EditForm(forms.Form):
    first_name = forms.CharField(max_length=64, label = "Имя")
    last_name = forms.CharField(max_length=64, label = "Фамилия")
    username = forms.CharField(max_length=64, label='username')
    email = forms.CharField(max_length=64, label = "Email")
    old_password = forms.CharField(widget=forms.PasswordInput, min_length=6, label='Текущий пароль')
    new_password = forms.CharField(widget=forms.PasswordInput, min_length=6, label='Новый пароль')
    rep_new_password = forms.CharField(widget=forms.PasswordInput, min_length=6, label='Повторите пароль')

    def clean_rep_new_password(self):
        data = self.cleaned_data
        if data['rep_new_password'] == data['new_password']:
            if data['old_password'] != data['new_password']:
                return data['new_password']
            else:
                raise ValidationError("Нельзя изменить пароль на текущий")
        else:
            raise ValidationError("Пароли не совпадают")

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import render
from .models import Category, Product


def index(request):
    categories = Category.objects.all()
    return render(request, 'index.html', {'categories': categories})


def product_category(request,slug):
    categories = Category.objects.all()
    category = Category.objects.get(slug=slug)
    products = Product.objects.filter(category=category)
    return render(request,'index.html',{'categories': categories,'products':products})

def more_info(request,id):
    tupl = get_object_or_404(Product, id=id)
    more_info = {'more_info': tupl}
    return render(request, 'more_info.html', more_info)

user/views.py
from django.contrib.auth.hashers import check_password
from django.shortcuts import render, redirect
from .forms import AuthForm, RegForm, EditForm
from django.contrib.auth import authenticate, login
import django.contrib.auth
from django.contrib.auth.models import User
from django.contrib import messages
from django.views.generic import View


def print_messages(request, errors):
    for field in errors:
        for error in field.errors:
            messages.error(request, error)


def my_account(request):
    return render(request, 'my-account.html', {'auth_form': AuthForm(), 'reg_form': RegForm()})


class EditAccount(View):
    def get(self, request):
        edit_form = EditForm(initial={'first_name':request.user.first_name,'last_name':request.user.last_name,'email': request.user.email, 'username':request.user.username})
        return render(request, 'edit-account.html', {'edit_form': edit_form})

    def post(self, request, *args, **kwargs):
        user = User.objects.get(id=request.user.id)
        username = user.username
        edit_password_form = EditForm(request.POST)
        if edit_password_form.is_valid():
            edit_password_form = edit_password_form.cleaned_data
            if not (check_password(edit_password_form['old_password'], user.password)):
                messages.error(request, "Неверный пароль")
            else:
                user.set_password(edit_password_form['new_password'])
                user.save()
                messages.info(request, "Пароль успешно изменён")
                user = authenticate(request, username=username, password=edit_password_form['new_password'])
                login(request, user)
        else:
            print_messages(request, edit_password_form)
        return redirect('user:my-account')


def registration(request):
    reg_info = RegForm(request.POST)
    if reg_info.is_valid():
        reg_info = reg_info.cleaned_data
        username = reg_info['email'].split('@')[0]
        user = User.objects.create_user(username, reg_info['email'], reg_info['password'])
        user.save()
        user = authenticate(request, username=username, password=reg_info['password'])
        login(request, user)
    return redirect('user:my-account')


def authorization(request):
    auth_info = AuthForm(request.POST)
    if auth_info.is_valid():
        auth_info = auth_info.cleaned_data
        if (len(User.objects.filter(email=auth_info['login'])) > 0):
            u = User.objects.get(email=auth_info['login'])
        elif (len(User.objects.filter(username=auth_info['login'])) > 0):
            u = User.objects.get(username=auth_info['login'])
        else:
            messages.error(request, 'Такого пользователя нет')
            return redirect('user:my-account')
        user = authenticate(request, username=u.username, password=auth_info['password'])
        login(request, user)
    return redirect('user:my-account')


def logout(request):
    django.contrib.auth.logout(request)
    return redirect('user:my-account')

shop/templates/index.html
{% extends 'base.html' %}
{% block title %}Главная{% endblock %}
{% block body %}
    <br>
    {% for product in products %}
        {{ product.title }}
        <br>
        <img src="http://127.0.0.1:8000/{{ product.img}}">
        <br>
        {{ product.price }} <a href="{% url 'shop:more_info' product.id %}">Подробнее</a>
    {% endfor %}

{% endblock %}

shop/templates/more_info.html
{% extends 'base.html' %}

{% block title %}Подробнее{% endblock %}

{% block body %}
    <br>
    {% if more_info %}
        <h1>{{ more_info.title }}</h1>
        {{ more_info.description }}
        {{ more_info.price }}
    {% endif %}
{% endblock %}

user/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<style>
    input {
        display: block;
    }
</style>
{% block notifications %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}
<a href="{% url 'shop:index' %}">Лого</a>
<br>
{% for category in categories %}
    <a href="{% url 'shop:product-category' category.slug %}">{{ category }}</a>->{{ category.parent }}<br>
{% endfor %}
<a href="{% url 'user:my-account' %}">Мой аккаунт</a>
Корзина:
{% block basket %}
    Пусто
{% endblock %}
{% block body %}
{% endblock %}
</body>
</html>

user/templates/edit-account.html
{% extends 'my-account.html' %}
{% block my_account %}
    <form method="post" action="{% url 'user:authorization' %}">
        {% csrf_token %}
        {{ edit_form }}
        <input type="submit" value="Сохранить изменения">
    </form>
{% endblock %}

user/templates/my-account.html
{% extends 'base.html' %}
{% block title %}Мой аккаунт{% endblock %}
{% block body %}
    {% if not user.is_authenticated %}
        <form method="post" action="{% url 'user:authorization' %}">
            {% csrf_token %}
            {{ auth_form }}
            <input type="submit" value="Войти">
        </form>
        <form method="post" action="{% url 'user:registration' %}">
            {% csrf_token %}
            {{ reg_form }}
            <input type="submit" value="Зарегистрироваться">
        </form>
    {% else %}<br>
        Hi, {{ user.username }}<br>
        <a href="{% url 'user:logout' %}">Консоль</a><br>
        <a href="{% url 'user:logout' %}">Заказы</a><br>
        <a href="{% url 'user:logout' %}">Адреса</a><br>
        <a href="{% url 'user:edit-account' %}">Профиль</a><br>
        <a href="{% url 'user:logout' %}">Выйти</a><br>
        {% block my_account %}{% endblock %}
    {% endif %}
{% endblock %}